workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" '
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG =~ /^v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,3}(-([a-zA-Z0-9])*)?$/

stages:
  - lint
  - test
  - release

linting:
  stage: lint
  image: node:18
  script:
    - npm ci --progress=false
    - npm run lint
    - NPM_PROJECT_VER=$(npm -s run env echo '$npm_package_version')
    - echo "NPM_PROJECT_VER=$NPM_PROJECT_VER" >> linting.env
  artifacts:
    when: on_success
    reports:
      dotenv: linting.env
    paths:
      - node_modules/

testing:
  stage: test
  image: node:18
  dependencies:
    - "linting"
  before_script:
    - npm ci --progress=false
  script:
    - npm run test:unit
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" '
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,3}(-([a-zA-Z0-9])*)?$/

publish:
  stage: release
  image: node:18
  dependencies:
    - "testing"
  before_script:
    - npm ci --progress=false
  script:
    - npm version  --no-git-tag-version  $CI_COMMIT_TAG
    - npm run build
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,3}(-([a-zA-Z0-9])*)?$/
